# -*- coding: utf-8 -*-
"""Untitled55.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZWJjODV-vKC_xG6PPvo9P5bwb9nAEVT-
"""
import streamlit as st
import hashlib
import json
import os
import random
import pandas as pd
from datetime import datetime

# ==========================================================
# ---------------------- FILE PATHS -------------------------
# ==========================================================

USER_FILE = "users.json"
OTP_FILE = "otp_codes.json"
AUDIT_FILE = "audit_log.csv"
FORM_FILE = "insurance_data.csv"

# ==========================================================
# ----------------- PASSWORD HASHING (SHA256) ---------------
# ==========================================================

def hash_password(pwd):
    return hashlib.sha256(pwd.encode()).hexdigest()

def verify_password(input_password, stored_hash):
    return hash_password(input_password) == stored_hash

# ==========================================================
# ---------------------- INIT FILES -------------------------
# ==========================================================

def init_files():
    # Setup default users if file missing
    if not os.path.exists(USER_FILE):
        users = {
            "admin": {
                "password": hash_password("admin123"),
                "role": "Admin"
            },
            "staff": {
                "password": hash_password("staff123"),
                "role": "Staff"
            },
            "viewer": {
                "password": hash_password("viewer123"),
                "role": "Viewer"
            }
        }
        with open(USER_FILE, "w") as f:
            json.dump(users, f, indent=4)

    # OTP store
    if not os.path.exists(OTP_FILE):
        with open(OTP_FILE, "w") as f:
            json.dump({}, f)

    # Audit log
    if not os.path.exists(AUDIT_FILE):
        df = pd.DataFrame(columns=["Timestamp", "Username", "Role", "Action"])
        df.to_csv(AUDIT_FILE, index=False)

init_files()

# ==========================================================
# ---------------------- HELPERS ----------------------------
# ==========================================================

def load_users():
    with open(USER_FILE, "r") as f:
        return json.load(f)

def save_users(users):
    with open(USER_FILE, "w") as f:
        json.dump(users, f, indent=4)

def log_action(username, role, action):
    df = pd.DataFrame([[datetime.now(), username, role, action]],
                      columns=["Timestamp", "Username", "Role", "Action"])
    df.to_csv(AUDIT_FILE, mode="a", header=False, index=False)

def generate_otp(username):
    otp = str(random.randint(100000, 999999))
    with open(OTP_FILE, "r") as f:
        otps = json.load(f)
    otps[username] = otp
    with open(OTP_FILE, "w") as f:
        json.dump(otps, f)
    return otp  # Shown as simulated “email”

def verify_otp(username, otp_input):
    with open(OTP_FILE, "r") as f:
        otps = json.load(f)
    return otps.get(username, None) == otp_input

def load_form_data():
    if os.path.exists(FORM_FILE):
        return pd.read_csv(FORM_FILE)
    return pd.DataFrame()

def save_form(entry):
    df_new = pd.DataFrame([entry])
    if os.path.exists(FORM_FILE):
        df_new.to_csv(FORM_FILE, mode='a', header=False, index=False)
    else:
        df_new.to_csv(FORM_FILE, index=False)

# ==========================================================
# ---------------------- SESSION VARS -----------------------
# ==========================================================

if "logged_in" not in st.session_state:
    st.session_state.logged_in = False
if "role" not in st.session_state:
    st.session_state.role = None
if "username" not in st.session_state:
    st.session_state.username = None
if "otp_sent" not in st.session_state:
    st.session_state.otp_sent = False

# ==========================================================
# ---------------------- MAIN MENU --------------------------
# ==========================================================

st.title("🔐 Multi-User Insurance Automation System")

menu = st.sidebar.selectbox("Menu", ["📝 Fill Form", "🔐 Login", "📊 Dashboard"])

# ==========================================================
# ---------------------- LOGIN PAGE -------------------------
# ==========================================================

if menu == "🔐 Login":
    st.header("User Login (OTP Protected)")

    users = load_users()
    username = st.text_input("Username")
    password = st.text_input("Password", type="password")

    if st.button("Send OTP"):
        if username in users:
            stored_hash = users[username]["password"]
            if verify_password(password, stored_hash):
                otp = generate_otp(username)
                st.session_state.otp_sent = True
                st.success(f"✅ OTP sent (SIMULATED): **{otp}**")
            else:
                st.error("❌ Incorrect password")
        else:
            st.error("❌ User not found")

    if st.session_state.otp_sent:
        otp_input = st.text_input("Enter OTP")
        if st.button("Login"):
            if verify_otp(username, otp_input):
                st.session_state.logged_in = True
                st.session_state.username = username
                st.session_state.role = users[username]["role"]
                log_action(username, st.session_state.role, "Logged in")
                st.success(f"✅ Login successful! Welcome **{username}**")
            else:
                st.error("❌ Invalid OTP")

# ==========================================================
# ---------------------- INSURANCE FORM ---------------------
# ==========================================================

if menu == "📝 Fill Form":
    st.header("Insurance Form")

    name = st.text_input("Name")
    gender = st.selectbox("Gender", ["Male", "Female", "Other"])
    age = st.number_input("Age", 0, 120)
    contact = st.text_input("Contact Number")
    dob = st.date_input("Date of Birth")

    hospital = st.text_input("Hospital Name")
    policy = st.text_input("Policy Number")

    if st.button("Submit Form"):
        entry = {
            "Timestamp": datetime.now(),
            "Name": name,
            "Gender": gender,
            "Age": age,
            "Contact": contact,
            "DOB": dob,
            "Hospital": hospital,
            "Policy": policy
        }
        save_form(entry)

        if st.session_state.logged_in:
            log_action(st.session_state.username, st.session_state.role, "Submitted Form")

        st.success("✅ Form submitted successfully!")

# ==========================================================
# ---------------------- DASHBOARD --------------------------
# ==========================================================

if menu == "📊 Dashboard":

    if not st.session_state.logged_in:
        st.warning("🔐 Please login to access the dashboard")
        st.stop()

    role = st.session_state.role
    username = st.session_state.username

    st.header(f"📊 Dashboard ({role})")
    log_action(username, role, "Opened Dashboard")

    df = load_form_data()

    # -------- Viewer (Read-only) --------
    if role == "Viewer":
        st.subheader("Read-Only Records")
        st.dataframe(df)

    # -------- Staff (Filter + view only) --------
    if role == "Staff":
        st.subheader("Staff Access")
        name_filter = st.text_input("Filter by Name")
        filtered = df[df["Name"].str.contains(name_filter, case=False)] if name_filter else df
        st.dataframe(filtered)

    # -------- Admin (Full Access) --------
    if role == "Admin":
        st.subheader("Admin Panel: Full Access")
        st.dataframe(df)

        st.subheader("👤 Audit Log")
        audit = pd.read_csv(AUDIT_FILE)
        st.dataframe(audit)

        # Add new user
        st.subheader("➕ Add New User")
        new_user = st.text_input("New Username")
        new_pass = st.text_input("New Password", type="password")
        new_role = st.selectbox("Role", ["Admin", "Staff", "Viewer"])

        if st.button("Create User"):
            users = load_users()
            if new_user in users:
                st.error("❌ Username already exists")
            else:
                users[new_user] = {
                    "password": hash_password(new_pass),
                    "role": new_role
                }
                save_users(users)
                log_action(username, role, f"Created user: {new_user}")
                st.success("✅ User created successfully!")

    # Logout button
    if st.button("Logout"):
        log_action(username, role, "Logged out")
        st.session_state.logged_in = False
        st.session_state.username = None
        st.session_state.role = None
        st.success("✅ Successfully logged out")
